### ISSUE TITLE
Facebook ban

### ISSUE THREAD

**Issue by t3bld** [PedjPedj/Facebook-gc-bot#9]
Do you know what the ban rate is? Does Facebook detect unconventional behavior or does it only block on user recommendation when the profile is reported?

**Comment by ArkasDev** [comment]
I am really interested in working on your project, contact me via mail@davidtheobald.de

**Comment by PedjPedj** [comment]
> Do you know what the ban rate is? Does Facebook detect unconventional behavior or does it only block on user recommendation when the profile is reported?

I honestly don't have sure answers for this...
- I'm not sure what the ban rate is.
- I think facebook are only suspicious to newly created accounts that has no other activity than send messages.
- If bot is reported by other users I'm think facebook look into it... if not reported I think the bot will be fine.
